---
- hosts: nexus.depi.local
  become: yes
  become_method: sudo
  tasks:

    # 1. Install required dependencies
    - name: Install required system packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    # 2. Add Docker GPG key and repository
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    # 3. Install Docker and Docker Compose
    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: present

    # 4. Ensure Docker service is running
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    # 5. Copy Docker Compose file to remote host
    - name: Copy Docker Compose file
      copy:
        src: files/docker-compose.yml
        dest: /home/{{ ansible_user }}/docker-compose.yml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    # 6. Run Docker Compose
    - name: Run Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/{{ ansible_user }}/
