---
- name: Install and configure Prometheus and Grafana
  hosts: monitor
  become: true
  become_method: sudo
  tasks:

  - name: Update apt and install dependencies
    apt:
      update_cache: yes
      name: 
        - wget
        - curl
        - apt-transport-https
        - software-properties-common
      state: present

  # Install Prometheus
  - name: Create Prometheus user and directories
    user:
      name: prometheus
      shell: /bin/false

  - name: Create Prometheus directories
    file:
      path: "{{ item }}"
      state: directory
      owner: prometheus
      group: prometheus
      mode: '0755'
    loop:
      - /etc/prometheus
      - /var/lib/prometheus

  - name: Download Prometheus
    get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v2.44.0/prometheus-2.44.0.linux-amd64.tar.gz
      dest: /tmp/prometheus.tar.gz

  - name: Extract Prometheus
    unarchive:
      src: /tmp/prometheus.tar.gz
      dest: /tmp/
      remote_src: yes

  - name: Move Prometheus binaries prometheus
    command: mv /tmp/prometheus-2.44.0.linux-amd64/prometheus /usr/local/bin/

  - name: Move Prometheus binaries promtool
    command: mv /tmp/prometheus-2.44.0.linux-amd64/promtool /usr/local/bin/

  - name: Move Prometheus configuration files consoles
    command: mv /tmp/prometheus-2.44.0.linux-amd64/consoles /etc/prometheus/

  - name: Move Prometheus configuration files console_libraries
    command: mv /tmp/prometheus-2.44.0.linux-amd64/console_libraries /etc/prometheus/

  - name: Move Prometheus configuration files
    command: mv /tmp/prometheus-2.44.0.linux-amd64/prometheus.yml /etc/prometheus/

  - name: Set Prometheus file permissions
    file:
      path: "{{ item }}"
      owner: prometheus
      group: prometheus
    loop:
      - /usr/local/bin/prometheus
      - /usr/local/bin/promtool
      - /etc/prometheus/consoles
      - /etc/prometheus/console_libraries
      - /etc/prometheus/prometheus.yml

  - name: Create Prometheus service file
    copy:
      dest: /etc/systemd/system/prometheus.service
      content: |
        [Unit]
        Description=Prometheus Service
        Wants=network-online.target
        After=network-online.target

        [Service]
        User=prometheus
        ExecStart=/usr/local/bin/prometheus \
          --config.file=/etc/prometheus/prometheus.yml \
          --storage.tsdb.path=/var/lib/prometheus \
          --web.console.templates=/etc/prometheus/consoles \
          --web.console.libraries=/etc/prometheus/console_libraries

        [Install]
        WantedBy=multi-user.target

  - name: Reload systemd and start Prometheus
    systemd:
      name: prometheus
      daemon_reload: yes
      enabled: yes
      state: started

  # Install Grafana
  - name: Add Grafana APT key
    apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present

  - name: Add Grafana repository
    apt_repository:
      repo: "deb https://packages.grafana.com/oss/deb stable main"
      state: present

  - name: Install Grafana
    apt:
      name: grafana
      state: present

  - name: Enable and start Grafana service
    systemd:
      name: grafana-server
      enabled: yes
      state: started

  - name: Configure firewall rules (if needed)
    ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
    loop:
      - 3000   # Grafana default port
      - 9090   # Prometheus default port
