version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9999:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana2
    ports:
      - "3333:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
      - GF_SECURITY_ADMIN_USER=devops-user
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
